### ISSUE TITLE
Thread safe API

### ISSUE THREAD

**Issue by kontura** [zchunk/zchunk#106]
We have been seeing crashes in `createrepo_c` due to its multi-threading nature.

See: https://github.com/rpm-software-management/createrepo_c/issues/386

Would it be possible to make the API thread safe or is this something we have to work around in `createrepo_c`?

**Comment by jdieter** [comment]
@kontura, I'm not averse to the idea, but how would you see this working?  In other words, if multiple threads are reading the file at the same time, what should happen?  Should there be some form of locking, with one thread reading data, and then the next and then the next?

I just want to understand what exactly the behavior is that you're looking for when using multiple threads.

**Comment by kontura** [comment]
`createrepo_c` is just trying to read different files in different threads.


The problem seems to be with global [`zck_none` ](https://github.com/zchunk/zchunk/blob/main/src/lib/error.c#L38), it is described in the issue in a comment.

In general I would expect that reading, even the same file from multiple threads, wouldn't need a lock no?
