### ISSUE TITLE
hex_to_int does not handle bogus values properly

### ISSUE THREAD

**Issue by maage** [zchunk/zchunk#11]
https://github.com/zchunk/zchunk/blob/master/src/lib/zck.c#L85
As far as I can see hex_to_int does return wrong response if your input is not hex.

Another simpler to understand hex to int algorithm with possibility to handle bogus values.

https://github.com/gcc-mirror/gcc/blob/master/libiberty/hex.c
https://github.com/gcc-mirror/gcc/blob/master/include/libiberty.h#L383

**Comment by jdieter** [comment]
You're absolutely right.  Thanks so much for reporting this.

I'm not a fan of how libiberty handles it, but I've added sanity checking and a test case to verify that the sanity checking actually works.  See 88327bde59edd3aadd9381d591a32f26dbf04d24
