### ISSUE TITLE
No bundling libraries

### ISSUE THREAD

**Issue by ignatenkobrain** [zchunk/zchunk#2]
Please, unbundle sha1/sha2 stuff. You could use openssl for those.

**Comment by jdieter** [comment]
There's now the option to not use the bundled sha1/sha2 libraries and use openssl instead, which is the default if openssl is installed.  I want to leave the bundled libraries available so zchunk can be compiled with minimal dependencies if necessary.

See 45c5c98f9fb49ca4b76af87e0fcfcab766a06cd8.

**Comment by mlschroe** [comment]
(I find it absurd that glibc doesn't come with support for md5/sha1/sha2 hashes. The code is there anyway for password hashing, it's just not exposed.
Sorry for the rant.)
