### ISSUE TITLE
Cross-platform support?

### ISSUE THREAD

**Issue by wolfv** [zchunk/zchunk#24]
I was trying to build zchunk on OS X but there were some issues (specifically `<endian.h>` is not in the right place.

Are you interested in upstreaming support for OS X and (eventually) Windows?

This is part of an effort in making `librepo` more widely available through `conda` which is a cross-platform package manager, and using it in a project called `mamba` (github.com/quantstack/mamba) (that is a drop-in replacement for conda).

I know that zchunk might not (immediately) be required for mamba + libsolv + librepo to work but anyways, just wanted to be a good citizen in Open Source and let you know.

The conda-forge "recipe" for building zchunk is here: http://github.com/conda-forge/zchunk-feedstock
Let me know if you're interested in being part of this.

**Comment by jdieter** [comment]
I will happily upstream support for any operating system, especially if there is automated testing on those operating systems.  PRs are more than welcome!

**Comment by jdieter** [comment]
FWIW, zchunk-1.1.7 has added support for FreeBSD.  I'm not sure how difficult it would be to expand that support to OS X.

**Comment by davidbrochart** [comment]
The latest conda-forge build (which uses zchunk 1.1.7) now has a problem with the `argp` library on OSX (see [the logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=244109&view=logs&jobId=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b)):
```
meson.build:32:4: ERROR: C shared or static library 'argp' not found
```

**Comment by davidbrochart** [comment]
We made some progress after packaging [`argp` for OSX](https://github.com/conda-forge/argp-standalone-feedstock), but [one test fails](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=247027&view=logs&jobId=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b):
```
26/26 compress manual file - dict            FAIL           0.83s (exit status 1)

--- command ---
16:51:31 $SRC_DIR/builddir/test/shacheck src/zck LICENSE.manual.dict.fodt.zck 4e86b47410a3a5090c7d60040d24d8d390c31f16f96ea112c8f153888eaf8c6e -D $SRC_DIR/test/files/LICENSE.dict -m -s <text: -o LICENSE.manual.dict.fodt.zck $SRC_DIR/test/files/LICENSE.fodt
--- stdout ---
LICENSE.manual.dict.fodt.zck:
Calculated checksum: (SHA-256)120fd037006403d3747270620209abfa1112c783b246a15126b202bee7d87e62
Expected checksum: (SHA-256)4e86b47410a3a5090c7d60040d24d8d390c31f16f96ea112c8f153888eaf8c6e
Checksums don't match!
-------
```

**Comment by jdieter** [comment]
> We made some progress after packaging [`argp` for OSX](https://github.com/conda-forge/argp-standalone-feedstock), but [one test fails](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=247027&view=logs&jobId=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b):
> 
> ```
> 26/26 compress manual file - dict            FAIL           0.83s (exit status 1)
> 
> --- command ---
> 16:51:31 $SRC_DIR/builddir/test/shacheck src/zck LICENSE.manual.dict.fodt.zck 4e86b47410a3a5090c7d60040d24d8d390c31f16f96ea112c8f153888eaf8c6e -D $SRC_DIR/test/files/LICENSE.dict -m -s <text: -o LICENSE.manual.dict.fodt.zck $SRC_DIR/test/files/LICENSE.fodt
> --- stdout ---
> LICENSE.manual.dict.fodt.zck:
> Calculated checksum: (SHA-256)120fd037006403d3747270620209abfa1112c783b246a15126b202bee7d87e62
> Expected checksum: (SHA-256)4e86b47410a3a5090c7d60040d24d8d390c31f16f96ea112c8f153888eaf8c6e
> Checksums don't match!
> -------
> ```

What version of zstd are you compiling against?

**Comment by davidbrochart** [comment]
I believe I fixed this issue, thanks @jdieter!

**Comment by wolfv** [comment]
we should be compiling again 1.4.5 (https://anaconda.org/conda-forge/zstd)

**Comment by jdieter** [comment]
> I believe I fixed this issue, thanks @jdieter!

Perfect, then I'll close this.

**Comment by wolfv** [comment]
We don’t have windows yet :)

**Comment by davidbrochart** [comment]
Yes, I should have mentioned that the *OSX* issue was fixed.

**Comment by jdieter** [comment]
> We don’t have windows yet :)

True. Ok, let's reopen then.

**Comment by nima2007** [comment]
#35

**Comment by jdieter** [comment]
Ok, with PR #44, we now build on Cygwin.  I'm closing this issue, but, if there's another platform that we can't build on (and we should), please re-open (or, even better, submit a PR that fixes the bug :grin:).
