### ISSUE TITLE
zchunk not working in fedora 32

### ISSUE THREAD

**Issue by legacychimera247** [zchunk/zchunk#25]
hi, asked in ask.fedora but none seems to know the answer so i figured out asking on here
simply enough, from fedora 32 zchunk is enabled by default for the updates, but it's not working at all, it always give me this error

`Fedora Modular 32 - x86_64 - Updates             93 kB/s | 150 kB     00:01    
Errors during downloading metadata for repository 'updates-modular':
  - Curl error (23): Failed writing received data to disk/application for http://fedora.mirror.garr.it/fedora/linux/updates/32/Modular/x86_64/repodata/d66f8672b570d6c2782ff1f8db3508a2d99d127c014e1120c0dc68c320d49ae4-filelists.xml.zck [Failed writing body (0 != 758)]
  - Curl error (23): Failed writing received data to disk/application for http://fedora.mirror.garr.it/fedora/linux/updates/32/Modular/x86_64/repodata/0f2d82d82ea58f54c7901f81709d914cad2223d2e005485b2edda48733835e64-primary.xml.zck [Failed writing body (0 != 565)]
Errore: Failed to download metadata for repo 'updates-modular': Yum repo downloading error: Downloading error(s): repodata/0f2d82d82ea58f54c7901f81709d914cad2223d2e005485b2edda48733835e64-primary.xml.zck - Download failed: Curl error (23): Failed writing received data to disk/application for http://fedora.mirror.garr.it/fedora/linux/updates/32/Modular/x86_64/repodata/0f2d82d82ea58f54c7901f81709d914cad2223d2e005485b2edda48733835e64-primary.xml.zck [Failed writing body (0 != 565)]; repodata/d66f8672b570d6c2782ff1f8db3508a2d99d127c014e1120c0dc68c320d49ae4-filelists.xml.zck - Download failed: Curl error (23): Failed writing received data to disk/application for http://fedora.mirror.garr.it/fedora/linux/updates/32/Modular/x86_64/repodata/d66f8672b570d6c2782ff1f8db3508a2d99d127c014e1120c0dc68c320d49ae4-filelists.xml.zck [Failed writing body (0 != 758)]`

with zchunk disabled, everything is ok
don't know if it's the right place to report but i thought you may be interested...

**Comment by jdieter** [comment]
Normally I'd prefer these reports be in https://bugzilla.redhat.com against the `zchunk` component.  Having said that, I don't mind trying to figure this out here.  Do you mind enabling zchunk again and then running `dnf --verbose update` and see if you get the error?  If so, can you please open a ticket on bugzilla and attach `librepo.log` (I don't think GitHub will allow you to do so)?

**Comment by jdieter** [comment]
I'd also be interested if you're going through a proxy or anything like that.

**Comment by legacychimera247** [comment]
hi, i've created a bug report on bugzilla

that's the link
https://bugzilla.redhat.com/show_bug.cgi?id=1830512

**Comment by jdieter** [comment]
Perfect!  I'm going to close this and we'll continue there.
