### ISSUE TITLE
The 1.1.6 tag is not on the master branch

### ISSUE THREAD

**Issue by ppentchev** [zchunk/zchunk#27]
Hi,

I'm not sure if it is on purpose, but it would kind of help with downstream packaging and also with submitting merge requests if the master branch were to be fast-forwarded to the 1.1.6 tag :)

Thanks a lot for your work!

G'luck,
Peter

**Comment by jdieter** [comment]
Yeah, that was a goof.  No idea how it happened.  Fixed now.
