### ISSUE TITLE
Idea: put split string into dict

### ISSUE THREAD

**Issue by mlschroe** [zchunk/zchunk#3]
My impression is that the dictionary is somewhat tied to the split string, so it might be a good idea to use a custom format for the dictionary and store the split string into it.

I.e. if the dict comes from something like a package, createrepo should use the correct split string when creating zchunk data.

**Comment by jdieter** [comment]
The thing is that the split string is only used by the zck utility, not by libzck.  Createrepo splits based on the package xml (which just happens to be split on "<package "), but does things like merging the next package with the previous if they share srpms, so it's not an automatic split on a string.

As far as libzck goes, it doesn't care where you split your chunks, as long as you do it consistently from one version of the file to the next, so I'm not sure that the split string is actually useful.

**Comment by jdieter** [comment]
@mlschroe, I'm closing this, but feel free to reopen if you feel strongly that this would be an important feature.
