### ISSUE TITLE
Tests are failing on Mageia Cauldron

### ISSUE THREAD

**Issue by david-geiger** [zchunk/zchunk#34]
Hi,

Tests are failing with release 1.1.7 and latest 1.1.8:

Summary of Failures:

23/26 compress auto-chunked file - no dict   FAIL           0.08s (exit status 1)
24/26 compress auto-chunked file - dict      FAIL           0.14s (exit status 1)
25/26 compress manual file - no dict         FAIL           0.18s (exit status 1)
26/26 compress manual file - dict            FAIL           1.23s (exit status 1)

Ok:                 21  
Expected Fail:      1   
Fail:               4   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0 

Attached full build log:
[build.i586.0.20201229074903.log](https://github.com/zchunk/zchunk/files/5749990/build.i586.0.20201229074903.log)

Regards,
David

**Comment by jdieter** [comment]
Thanks, I've investigated and this appears to be related to some low-level changes in zstd-1.4.7 and later.  There's a simple fix, but I'd really prefer to do a more involved deterministic fix.

**Comment by jdieter** [comment]
Well, it looks like the more involved fix won't work as expected, so I've gone with the simple one. :(  This has been fixed in 1.1.9.

**Comment by jdieter** [comment]
Specifically in commit d2eae512bee09a4047cfe586de12f644d73b0736
