### ISSUE TITLE
Unable to download chunks from specific server

### ISSUE THREAD

**Issue by kontura** [zchunk/zchunk#40]
dnf (librepo) can't download zchunk chunks from this server https://mirror.sjtu.edu.cn/fedora/linux/updates/testing/33/Everything/x86_64/repodata/. I have also tested it out with just `zckdl` and it fails the same way.

The problem only happens when you already have some file (previous version of zck repodata) and you try to download a new version.

Specifically this works fine:

```

$ zckdl https://mirror.sjtu.edu.cn/fedora/linux/updates/testing/33/Everything/x86_64/repodata/5c488b889a158c7d2df79bfab19a567e89c691d2b41a926614dbc2426218c8aa-primary.xml.zck 
Missing chunks: 2007 
Downloaded 2055342 bytes
```

But with older file:

```

$ zckdl -s repodata/4489a23f150d13dd7e6775a7ee4d2ba567742171c9f50df4b9c44c44a52bacc7-primary.xml.zck https://mirror.sjtu.edu.cn/fedora/linux/updates/testing/33/Everything/x86_64/repodata/5c488b889a158c7d2df79bfab19a567e89c691d2b41a926614dbc2426218c8aa-primary.xml.zck 
Missing chunks: 269
multipart_extract: Unable to find multipart download range
Download failed: Failed writing received data to disk/application
Unable to find multipart download range
```

Yet from a different mirror it works as expected:
```
zckdl -s repodata/4489a23f150d13dd7e6775a7ee4d2ba567742171c9f50df4b9c44c44a52bacc7-primary.xml.zck https://dl.fedoraproject.org/pub/fedora/linux/updates/testing/33/Everything/x86_64/repodata/5c488b889a158c7d2df79bfab19a567e89c691d2b41a926614dbc2426218c8aa-primary.xml.zck
Missing chunks: 269
Tried downloading too many ranges, reducing to 127
Downloaded 285125 bytes
```

Therefore I would say the problem is with that specific mirror and I wanted to [report it](https://github.com/sjtug/mirror-requests/issues), but I don't know what is causing it since the server does appear to support ranges.

Can you investigate what is the issue so we know what to report to the mirror?

(note the urls I mentioned from the update-testing repo may change as the repo is updated)

**Comment by kontura** [comment]
Oh it looks like this was already reported some time ago: https://github.com/sjtug/mirror-requests/issues/167 but since its still happening probably not really resolved.

**Comment by jdieter** [comment]
I've found and fixed the problem in 276acf58954705cdd260494a17249c2686d60425 and released zchunk-1.1.11.  Fedora updates should be making it into updates-testing soon.  I'm closing this, but please re-open if it hasn't fixed the problem for you.

**Comment by skyzh** [comment]
Thanks for looking into this! As a maintainer of the SJTUG mirror, we are grateful for your assistance.

**Comment by skyzh** [comment]
After some investigation, the underlying issue may be related to the HTTP response writer of golang. https://github.com/golang/go/blob/master/src/net/http/response.go We would also report this to golang later.
