### ISSUE TITLE
Clarify chunk number in format documentation

### ISSUE THREAD

**Issue by mlschroe** [zchunk/zchunk#5]
The format documentation says
```
Chunk count
This is a count of the number of chunks in the zchunk file.
```

This is misleading, as further down there's a distinction between the "dict stream" and the "chunk stream". Please change the wording to
```
This is a count of the number of chunks in the zchunk file including the dictionary chunk.
```

**Comment by jdieter** [comment]
Thanks for picking up on this.  Fixed in 42e5ba29e3ea5e540fb13ffbec161e589e8b6ad0.
