### ISSUE TITLE
Read fails in zck.c with error "Unable to read from input file" when input file is more than 2GB

### ISSUE THREAD

**Issue by jaredhagel** [zchunk/zchunk#71]
When using the 'zck' command with an input file that is greater than SSIZE_MAX or about 2GB, the read function call in src\zck.c within main() fails to read the entire input file. Our input files are larger than 2GB because we hope to use zchunk with the 'Delta Update with SWUpdate' feature (https://sbabic.github.io/swupdate/delta-update.html) and our image files are larger than 2GB. Is zchunk designed to work with files larger than 2GB (SSIZE_MAX)? I'm trying to determine if this is a bug or zchunk just isn't designed to do this.

**Comment by jdieter** [comment]
This is a bug and one that I thought we had fixed.  Let me look into it.

**Comment by jdieter** [comment]
This is fixed in c74ff02747a3b00fef9e98346452ab99672d97b0 and has been released as part of zchunk-1.2.1.  Thanks for the report!

**Comment by jaredhagel** [comment]
No problem. Thanks for fixing :)
