### ISSUE TITLE
Windows builds broken

### ISSUE THREAD

**Issue by jdieter** [zchunk/zchunk#77]
Something has changed over the last few days on GitHub's Windows builders that's broken Windows builds.  I don't know Windows, so @wolfv, would you be willing to take a look and tell me if this is something that GitHub is doing wrong or if we need to fix something in zchunk?

**Comment by jdieter** [comment]
Following up on this, it looks like a problem with `argp-standalone`.

**Comment by wolfv** [comment]
I will fix it. I've switched to a new org for the argp-standalone fork in preparation of the release on conda-forge. Sorry for the hiccup.

**Comment by jdieter** [comment]
Fixed in #78
