### ISSUE TITLE
Clarify the value proposition now that zstd has an "rsyncable" mode

### ISSUE THREAD

**Issue by dralley** [zchunk/zchunk#86]
The README should expand a bit on which situations zchunk is a better choice than zstd compression with the rsyncable mode enabled.  

The current description is:

> zchunk is a compressed file format that splits the file into independent chunks. This allows you to only download changed chunks when downloading a new version of the file, and also makes zchunk files efficient over rsync.

The description of the zstd [`--rsyncable`](https://github.com/facebook/zstd/issues/1155) flag is:

> --rsyncable : compress using a rsync-friendly method (-B sets block size) 

I doubt this feature existed at the time zchunk was written but now that it does, it's worth doing a comparison and making the value proposition clear.

**Comment by jdieter** [comment]
Hey @dralley, do you mind taking a look at PR #87 and see if it sufficiently addresses your concerns?  It is a bit odd that we were making a big deal of zchunk files being rsyncable when that's hardly the main benefit of zchunk.

**Comment by jdieter** [comment]
@dralley, thanks for flagging this!
