### ISSUE TITLE
[RFE] disable intermediate copy in /tmp

### ISSUE THREAD

**Issue by martinetd** [zchunk/zchunk#89]
Matt Wood noticed that zchunk writes a considerably amount of data in a temporary file, causing /tmp to fill up and update to fail with swupdate delta updates:
https://groups.google.com/g/swupdate/c/_V94tAbje_U/m/XlP-0NbODwAJ

Looking at the code, `zck_init_write` opens a temp_fd in TMPDIR then `zck_close` calls `chunks_from_temp` which copies back from temp fd into the destination file.

I don't really see any reason not to write directly to the destination file as the "chunks_from_temp" just looks like a straightforward copy, what is the rationale behind it? Just not clobbering the destination file if there was an error through decompression? Perhaps the intent was allowing in place upgrade so the same file can be used as source and destination?
In case of regular files I'd suggest opening a temporary files next to the destination file and finishing with a rename like e.g. rsync does, but for embedded devices the fd will likely point to a block device and it'd be greatly appreciated if there could be a way to bypass the temp fd and write directly to the destination.
We don't care if the destination file is broken on failed update, source and destination image must be separate for A/B updates, and the system to be booted is only switched after everything else has been successful.

(by the way, `comp_init` checks `if (zck->temp_fd) ...` but the fd could very well be zero if stdin has been closed, I'm not sure that check makes sense currently)

Thanks!

**Comment by jdieter** [comment]
Ok, the problem here is that `zck_init_write()` is intended to be used when _creating_ a zchunk file, not when applying it.  We create a temporary file to store the actual chunk data because we need to keep on growing the header at the beginning of the file at the same time as we're adding chunks to the end of the file.

`swupdate` generates a header for an already existing file (in this case, a whole partition) by "creating" a new zchunk file using `zck_init_write`, with a "NULL" compression format, so only the header is actually written.

@sbabic, I see two potential fixes here:
1. Add in logic to not bother with the temporary fd when the output file is `/dev/null`.  This requires special handling of the string `/dev/null`, so I'm not a huge fan.
2. Add in a new public function, `zck_init_header` that will create just the header from any data that comes in.  Needless to say, the implementation will essentially do what you were already doing, while also ensuring that we don't create the temporary file

@sbabic, my preference would be 2, but what's your take?  Is there another option I'm missing?

**Comment by sbabic** [comment]
> `swupdate` generates a header for an already existing file (in this case, a whole partition) by "creating" a new zchunk file using `zck_init_write`, with a "NULL" compression format, so only the header is actually written.

And the header is not written - we can say that SWUpdate requires an in-memory computation for zck's header.

> 
> @sbabic, I see two potential fixes here:
> 
>     1. Add in logic to not bother with the temporary fd when the output file is `/dev/null`.  This requires special handling of the string `/dev/null`, so I'm not a huge fan.

This seems a hack -  I am also not a fan of this, it is expected that each unix tool is unaware of the output.

> 
>     2. Add in a new public function, `zck_init_header` that will create just the header from any data that comes in.  Needless to say, the implementation will essentially do what you were already doing, while also ensuring that we don't create the temporary file
> 

This, or we add a zck_set_option() that disable the write to a file.

> 
> @sbabic, my preference would be 2, but what's your take?

I dislike 1., too.

>  Is there another option I'm missing?

More or less, we need a way to disable the write of the file - it should be converted int oa flag in zck structure that is interpreted by write_data(), skipping the write to a file.

**Comment by jdieter** [comment]
> > ```
> > 2. Add in a new public function, `zck_init_header` that will create just the header from any data that comes in.  Needless to say, the implementation will essentially do what you were already doing, while also ensuring that we don't create the temporary file
> > ```
> 
> This, or we add a zck_set_option() that disable the write to a file.

I like this option and have created a PR, #91 that does this.  Please test and let me know if it achieves your goals.

**Comment by mattwood-microchip** [comment]
I'll try to test this tonight but might not get to it until Monday

**Comment by sbabic** [comment]
@mattwood-microchip , simple test on my site are okay. Just please test with this simple patch for SWUpdate:

diff --git a/handlers/delta_handler.c b/handlers/delta_handler.c
index 8dadc51..19a9173 100644
--- a/handlers/delta_handler.c
+++ b/handlers/delta_handler.c
@@ -990,6 +990,10 @@ static int install_delta(struct img_type *img,
                ERROR("Error setting HASH Type %s\n", zck_get_error(zckSrc));
                goto cleanup;
        }
+       if (!zck_set_ioption(zckSrc, ZCK_NO_WRITE, 0)) {
+               WARN("ZCK does not support NO Write, use huge amount of RAM %s\n", zck_get_error(zckSrc));
+               goto cleanup;
+       }
 
        if (!create_zckindex(zckSrc, in_fd, priv->srcsize)) {
                WARN("ZCK Header form %s cannot be created, fallback to full download",

if everything is okay, I will take care to add it to SWUpdate's mainine - thanks !

**Comment by mattwood-microchip** [comment]
@sbabic,

zck_set_ioption() for ZCK_NO_WRITE should be 1 not 0.  After fixing that I confirm these changes solve the RAM issue and swupdate gets further, but is killed by a signal 11 (segfault) in child PID for chunks_downloader.

I'll take a look at this tomorrow, but many thanks to you, @jdieter, and @martinetd!

**Comment by jdieter** [comment]
This has been fixed in 136ea4dbc9410843131b2627483cd2cc9d7d6c49.
